### ISSUE TITLE
JSON file config

### ISSUE THREAD

**Issue by l0rdx3n0** [seungjuchoi/telegram-control-torrent#11]
Hi!

We try to run it and doesn´t work:

> Traceback (most recent call last):
  File "telegram_torrent.py", line 398, in <module>
    config = parseConfig(CONFIG_FILE)
  File "telegram_torrent.py", line 375, in parseConfig
    js = json.loads(f.read())
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 8 (char 110)`

Do you had the same problem?

Thanks in advance!

**Comment by seungjuchoi** [comment]
I have no problem about that.
please check your JSON Syntax.

**Comment by nhs0912** [comment]
저도 위에 분처럼 같은 오류가 나네요 ㅠㅠㅠ

**Comment by nhs0912** [comment]
아! JSON에서 아이디 부분을 "" 로 앞뒤 붙여주었더니 되네요! 설정 샘플 파일에 "" 표시로 수정하는게 좋을거 같아요~
